### ISSUE TITLE
Control where the Virtual Environment is created

### ISSUE THREAD

**Issue by sreedta8** [t-kalinowski/tensorflow.rstudio.com#66]
Hi

I'm experimenting with "reticulate" and tensorflow & keras ecosystem for the first time. I have used R for 20+ years and Python by itself via Anaconda, but not integrated the two together.
One of the reasons, of course, is to use the DL tools such as TF and Keras from R. I would like to know how I can specify the creation of virtual environments in a location other than that what is chosen by default by the "install_keras()" function.

The problem I run into is that for some of my colleagues at work, the default is an online Documents folder (MS One Drive) and the virtual environments are being created online and there is no way to use any of the DL functionality as the constant error is "No TensorFlow installation found" or some to that effect. Could I control where the virtual env is created, say for example under, "c:/users/batman/.virtualenv/joker/"?

**Comment by t-kalinowski** [comment]
There are a few ways:

-  You can set the environment variable `WORKON_HOME`. This will change the default location that reticulate will use to create and search for virtual environments that are not absolute paths. You can set this system wide in "System Properties" -> "Advanced" (Tab) -> "Environment Variables" (Button) here: 
<img width="402" alt="image" src="https://github.com/rstudio/tensorflow.rstudio.com/assets/8462255/2d5d5d2a-b5b3-4080-9521-8d4ddc44beac">

Or you can set it a .Renviron file
```
WORKON_HOME=~/../.virtualenvs
```
E.g.,:
```r
cat(sprintf("\nWORKON_HOME='%s'\n", normalizePath("~/../.virtualenvs", "/")),
           file = "~/.Renviron", append = TRUE))
``` 

Or you can set it in a .Rprofile, or in an R session directly:
```r
Sys.setenv(WORKON_HOME = "~/../.virtualenvs")
```

- You can also pass a path to the `envname` argument in `install_keras()` (and `reticulate::py_install()`, `virtualenv_create()`, etc.). 
```r
keras::install_keras(envname = "./.venv")
reticulate::use_virtualenv("./.venv")
```

**Comment by sreedta8** [comment]
@t-kalinowski Thank you!!!!! I know I cannot set through System Variables option. Good to know I can use multiple options to set via R
